config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  get 'users' =>'users#index' 
  get 'about' =>'tweets#about'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tweets#new'
  
  resources :tweets do
    collection do
      get 'desc'
    end
    collection do
      get 'like'
    end
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :authentication_keys => [:name]
         
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  has_many :comments, dependent: :destroy
  validates :name, presence: true 
  validates :profile, length: { maximum: 200 }
  mount_uploader :image, ImageUploader

  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
  
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["name = :value", { :value => name }]).first
    else
      where(conditions).first
    end
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      # サインアップ時にnameのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      # アカウント編集の時にnameとprofileのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :remember_me])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    tweet = Tweet.find(params[:tweet_id])
    comment = tweet.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path)
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_back(fallback_location: root_path)
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  layout "main2"
    def index
      
      if params[:search] == '' || params[:search] == nil
        @tweets= Tweet.all.order(id: "DESC").page(params[:page]).per(10)
      elsif params[:search] == 'newtweet'
        @tweets= Tweet.all.order(id: "DESC").page(params[:page]).per(10)
      elsif params[:search] == 'oldtweet'
        @tweets= Tweet.all.page(params[:page]).per(10)
      elsif params[:search] == 'liketweet'
        tweets = Tweet.includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
        @tweets= Kaminari.paginate_array(tweets).page(params[:page]).per(10)
      else
        search = params[:search]
        @tweets = Tweet.joins(:user).where("subject LIKE ? OR name LIKE ?", "%#{search}%", "%#{search}%").order(id: "DESC").page(params[:page]).per(10)
      end
      
    end
     
    def new
        @tweet = Tweet.new
    end

    def create
        tweet = Tweet.new(tweet_params)
        tweet.user_id = current_user.id
        tweet.created_date=Date.today
        if tweet.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end

    def show
        @tweet = Tweet.find(params[:id])
        @comments = @tweet.comments
        @comment = Comment.new
    end

    def edit
        @tweet = Tweet.find(params[:id])
    end

    def update
        tweet = Tweet.find(params[:id])
        if tweet.update(tweet_params)
          redirect_to :action => "show", :id => tweet.id
        else
          redirect_to :action => "new"
        end
    end

    def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy
        redirect_to action: :index
    end

    private
    def tweet_params
      params.require(:tweet).permit(:subject, :time, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    layout "main"
    def show
        @user = User.find(params[:id])
        @user.sum = @user.tweets.all.sum(:time)
        @user.level = @user.sum.to_i / 60
        @user_exp=100*(@user.sum%60)/60

        
        @tweets = @user.tweets.page(params[:page]).reverse_order
        @today_tweet =  @tweets.where(created_at: Time.zone.now.all_day)
        @yesterday_tweet = @tweets.where(created_at: 1.day.ago.all_day)
        @two_days_ago_tweet = @tweets.where(created_at: 2.days.ago.all_day)
        @three_days_ago_tweet = @tweets.where(created_at: 3.days.ago.all_day)
        @four_days_ago_tweet = @tweets.where(created_at: 4.days.ago.all_day)
        @five_days_ago_tweet = @tweets.where(created_at: 5.days.ago.all_day)
        @six_days_ago_tweet = @tweets.where(created_at: 6.days.ago.all_day)
        @tweet=Tweet.new
    end

    def index
        @users = User.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>レベスタ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <header>
      <h1>レベスタ</h1>
      <ul class="nav justify-content-end">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "マイページへ", user_path(current_user.id), class:"nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <a class="nav-link" href="/tweets">投稿一覧</a>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"nav-link"%> 
          </li>
        <% else %>
          <li class="nav-item dropdown">
            <%= link_to "ログイン", new_user_session_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path, class:"nav-link" %>
          </li>
        <% end %>
        
        
      </ul>
    </header>
    <%= yield %>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>レベスタ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <header>
      <a href="/tweets"><h1>レベスタ</h1></a>
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <%= link_to "説明", about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/tweets">投稿一覧</a>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"nav-link"%> 
          </li>
        <% else %>
          <li class="nav-item dropdown">
            <%= link_to "ログイン", new_user_session_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path, class:"nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "記録", new_tweet_path, class:"nav-link" %>
        </li>
        
      </ul>
    </header>
    <%= yield %>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/main2.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>レベスタ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <header>
      <a href="/tweets"><h1>レベスタ</h1></a>
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <%= link_to "説明", about_path, class:"nav-link" %>
        </li>
        <% if user_signed_in? %>
          
          <li class="nav-item">
            <%= link_to "マイページへ", user_path(current_user.id), class:"nav-link" %>
          </li>
        <% end %>
        
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"nav-link"%> 
          </li>
        <% else %>
          <li class="nav-item dropdown">
            <%= link_to "ログイン", new_user_session_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path, class:"nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "記録", new_tweet_path, class:"nav-link" %>
        </li>
        
      </ul>
    </header>
    <%= yield %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tweets/about.html.erb
<%= stylesheet_link_tag 'about', :media => "all" %>
<div class="background">
    <h4>アイコンについて</h4>
    <div class="main">
        <div class="explain">
            <p>0～19レベル</p>
                <%= image_tag 'さくらんぼの無料アイコン.svg', size: "50x50"%>
            <p>20～39レベル</p>
                <%= image_tag 'スイカの無料アイコン.svg', size: "50x50"%>
            <p>40～59レベル</p>
                <%= image_tag 'バナナの無料アイコン9.svg', size: "50x50"%>
            <p>60～79レベル</p>
                <%= image_tag '葡萄のフリーアイコン.svg', size: "50x50"%>
            <p>80～99レベル</p>
                <%= image_tag "テカテカしたリンゴのイラスト.svg", size: "50x50"%>
        </div>
        <div class="explain">
            <p>100～119レベル</p>
                <%= image_tag 'さくらんぼの無料アイコン (1).svg', size: "50x50"%>
            <p>120～139レベル</p>
                <%= image_tag 'スイカの無料アイコン (1).svg', size: "50x50"%>
            <p>140～159レベル</p>
                <%= image_tag 'バナナの無料アイコン9 (1).svg', size: "50x50"%>
            <p>160～179レベル</p>
                <%= image_tag '葡萄のフリーアイコン (1).svg', size: "50x50"%>
            <p>180～199レベル</p>
                <%= image_tag "テカテカしたリンゴのイラスト (1).svg", size: "50x50"%>
        </div>
        <div class="explain">
            <p>200～219レベル</p>
                <%= image_tag 'さくらんぼの無料アイコン (2).svg', size: "50x50"%>
            <p>220～239レベル</p>
                <%= image_tag 'スイカの無料アイコン (2).svg', size: "50x50"%>
            <p>240～259レベル</p>
                <%= image_tag 'バナナの無料アイコン9 (2).svg', size: "50x50"%>
            <p>260～279レベル</p>
                <%= image_tag '葡萄のフリーアイコン (2).svg', size: "50x50"%>
            <p>280～299レベル</p>
                <%= image_tag "テカテカしたリンゴのイラスト (2).svg", size: "50x50"%>
        </div>
    </div>
</div>

app/views/tweets/edit.html.erb
<%= stylesheet_link_tag 'edit', :media => "all" %>
<div class="background">
<%= form_for @tweet do |f| %>
  <div class="main">
    <div class="field">
      <div class="subject">        
        <%= f.label :教科, class:"form-image-label" do %>
          <div><i class="fas fa-book fa-fw"></i>教科　　　</div> 
          <div><%= f.text_field :subject, class:"form" %></div> 
        <% end %>   
      </div>
      <div class="time">
        <%= f.label :time, class:"form-image-label" do %>
          <div><i class="fas fa-clock fa-fw"></i>時間（分）</div> 
            <div><%= f.number_field :time, class:"form", :placeholder =>"半角で入力してください"  %></div> 
        <% end %>
      </div> 
      <div class="image">
        <%= f.label :image, class:"form-image-label" do %>
            <%= f.file_field :image, class:"message-hidden" %>
        <% end %>
      </div>
      <div class="submit">
        <%= button_tag :type => "submit", :class =>"btn btn-default btn-s-md" do %>
            <i class="fas fa-pen fa-lg"></i>編集する
        <% end %>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/tweets/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>
<%= page_entries_info @tweets %>
<div class="tweets-container">
    <div class="left-tweets"> 
     
      <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
        <%= text_field_tag :search %>
        <%= submit_tag '検索する', class:"btn-square-shadow"%>
      <% end %>
      <br>
      <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
        <%= select_tag("search", options_for_select([['---並べ替え選択---', ''], ['最新の投稿', 'newtweet'], ['古い投稿', 'oldtweet'], ['いいね順', 'liketweet']])) %>
        <%= submit_tag '並べ替える', class:"btn-square-shadow"  %>
      <% end %>
    </div>



      <% @tweets.each do |t| %>
      <div class="tweet">
      
        <div class="left-container">
          <div class="user">
            <%= image_tag t.user.image_url, size: "25x25" if t.user.image? %>
            <a href="/users/<%= t.user.id %>"><%= t.user.name %></a>
            <%case t.user.tweets.all.sum(:time)/60 %>
            <%when 0..19 then%>
              <%= image_tag 'さくらんぼの無料アイコン.svg', size: "20x20"%>
            <%when 20..39 then%>
              <%= image_tag 'スイカの無料アイコン.svg', size: "20x20"%>
            <%when 40..59 then%>
              <%= image_tag 'バナナの無料アイコン.svg', size: "20x20"%>
            <%when 60..79 then%>
              <%= image_tag '葡萄の無料アイコン.svg', size: "20x20"%>
            <%when 80..99 then%>
              <%= image_tag "テカテカしたリンゴのイラスト.svg", size: "20x20"%>

            <%when 100..119 then%>
              <%= image_tag 'さくらんぼの無料アイコン (2).svg', size: "20x20"%>
            <%when 120..139 then%>
              <%= image_tag 'スイカの無料アイコン (2).svg', size: "20x20"%>
            <%when 140..159 then%>
              <%= image_tag 'バナナの無料アイコン (2).svg', size: "20x20"%>
            <%when 160..179 then%>
              <%= image_tag '葡萄の無料アイコン (2).svg', size: "20x20"%>
            <%when 180..199 then%>
              <%= image_tag "テカテカしたリンゴのイラスト (2).svg", size: "20x20"%>

            <%when 200..219 then%>
              <%= image_tag 'さくらんぼの無料アイコン (3).svg', size: "20x20"%>
            <%when 220..239 then%>
              <%= image_tag 'スイカの無料アイコン (3).svg', size: "20x20"%>
            <%when 240..259 then%>
              <%= image_tag 'バナナの無料アイコン (3).svg', size: "20x20"%>
            <%when 260..279 then%>
              <%= image_tag '葡萄の無料アイコン (3).svg', size: "20x20"%>
            <%when 280..299 then%>
              <%= image_tag "テカテカしたリンゴのイラスト (3).svg", size: "20x20"%>
            <%else%>
              <i class="fas fa-crown"></i>
            <%end%>
          </div>
          <div class="image">
              <% if t.image.present? %>
              <%= image_tag t.image.url, size: "150x150"%>
            <% else %>
              <%= image_tag 'No_Image.jpg', size: "150x150"%>
            <% end %>
          </div>
        </div>
        <div class="right-container">
          <div class="contents">
            <i class="fas fa-book fa-fw"></i><%= t.subject %>
            <br>
            <i class="fas fa-clock fa-fw"></i><%= t.time %>分
          </div>
          <div class="like">
            <% if user_signed_in? %>
              <% if current_user.already_liked?(t) %>
                  <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
                      <i class="fas fa-heart"></i><%= t.likes.count %>
                  <% end %>
              <% else %>
                  <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
                      <i class="far fa-heart"></i><%= t.likes.count %>
                  <% end %>
              <% end %>
            <% else %>
              <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
          </div>
    
          <div class="others">
            <%= link_to "詳細", tweet_path(t.id) %>
            <% if user_signed_in? %>
              <% if current_user.id == t.user_id %>  
                <%= link_to "編集", edit_tweet_path(t.id) %>
                <%= link_to "削除", tweet_path(t.id), method: :delete %>
              <% elsif current_user.admin? %>
                <%= link_to "管理者用編集", edit_tweet_path(t.id) %>
                <%= link_to "管理者用削除", tweet_path(t.id), method: :delete %>
              <% end %> 
            <% end %>
          </div>
          <p class="time">投稿日時　<%=  t.created_at.to_s(:datetime_jp)%></p>
        </div>
      </div>
    <% end %> 

    <% if user_signed_in? %>
      <% if current_user.admin? %>
        <%= link_to "秘密のページへ", users_path %>
      <% end %>
    <% end %>   
  <%= paginate @tweets %>
</div>

app/views/tweets/show.html.erb
<%= stylesheet_link_tag 'show', :media => "all" %>

<div class="main-container">
  <div class="user">
    <%= image_tag @tweet.user.image_url, size: "70x70" if @tweet.user.image? %>
    <a href="/users/<%= @tweet.user.id %>"><%= @tweet.user.name %></a>
  </div>
  <div class="tweet">
    <p>教科：<%= @tweet.subject %></p>
    <p>時間：<%= @tweet.time %>分</p>
    <p><%= @tweet.created_at.to_s(:datetime_jp) %></p>
    <% if user_signed_in? %>
        <% if current_user.already_liked?(@tweet) %>
            <%= link_to tweet_like_path(@tweet), method: :delete do %>
              <i class="fas fa-heart"></i><%= @tweet.likes.count %>
            <% end %>
        <% else %>
            <%= link_to tweet_likes_path(@tweet), method: :post do %>
              <i class="far fa-heart"></i><%= @tweet.likes.count %>
            <% end %>
        <% end %>
    <% else %>
        <i class="far fa-heart"></i><%= @tweet.likes.count %>
    <% end %>
    <div class="edit">
      <%= link_to "編集する", edit_tweet_path(@tweet.id) %>
    </div>
  </div>


  <div class="like">
    <h3>いいねしたユーザー</h3>
    <% @tweet.liked_users.each do |user| %>
      <li><a href="/users/<%= user.id %>"><%= user.name %></a></li>
    <% end %>
  </div>

  <% if user_signed_in? %>
      <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
        <%= f.text_area :content %>
        <%= button_tag type: "submit" do %>
          <i class="far fa-comments"></i> コメントする
        <% end %>
      <% end %>
  <% end %>
  <div class="comment-wrapper">
    <h3>コメント一覧</h3>
    <% @comments.each do |c| %>
      <div>
        <%= image_tag c.user.image_url, size: "25x20" if c.user.image? %>
        <%= c.user.name unless c.user.blank? %>
        <br>
        <%= c.content %>
      </div>
      <%= link_to "コメント削除", tweet_comment_path(@tweet,c), method: :delete %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
 <% if user_signed_in? %>
   <% if current_user.admin? %>
     <% sum = 0 %>
       <% @users.each do |u| %>
         <p>メアド:<%= u.email %></p>
         <p>名前:<%= u.name %>さん</p>
       <% sum += 1 %>
       <% end %>
     <p>登録者合計：<%= sum %></p>
    <% end %>
  <% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードを忘れましたか?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>